package com.example.hungdt2;

import com.example.hungdt2.auth.dto.RegisterRequest;
import com.example.hungdt2.common.ApiResponse;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class PasswordResetIntegrationTest {

    @org.springframework.boot.test.web.server.LocalServerPort
    private int port;

    private org.springframework.web.client.RestTemplate rest = new org.springframework.web.client.RestTemplate();

    @Autowired
    private com.example.hungdt2.sms.TwilioVerifyService twilioServiceBean;

    @Test
    public void requestVerifyResetFlow() throws Exception {
        String base = "http://localhost:" + port;

        // Use a local-format phone (starting with 0). Service should normalize to +84 for Twilio
        String phone = "0367189928";
        RegisterRequest reg = new RegisterRequest("u_for_reset","u_for_reset@example.com","InitialP@ss1",phone,"User Reset");
        var r1 = rest.postForEntity(base + "/auth/register", reg, ApiResponse.class);
        Assertions.assertEquals(HttpStatus.CREATED, r1.getStatusCode());

        // prepare a map to capture OTPs generated by the mock Twilio service
        java.util.concurrent.ConcurrentHashMap<String, String> sent = new java.util.concurrent.ConcurrentHashMap<>();
        org.mockito.Mockito.doAnswer(invocation -> {
            String phoneArg = invocation.getArgument(0);
            String code = String.format("%06d", new java.util.Random().nextInt(1_000_000));
            sent.put(phoneArg, code);
            return null;
        }).when(twilioServiceBean).sendVerification(org.mockito.ArgumentMatchers.anyString());

        org.mockito.Mockito.when(twilioServiceBean.checkVerification(org.mockito.ArgumentMatchers.anyString(), org.mockito.ArgumentMatchers.anyString()))
            .thenAnswer(invocation -> {
                String p = invocation.getArgument(0);
                String c = invocation.getArgument(1);
                return c != null && c.equals(sent.get(p));
            });

        // request OTP (mock Twilio will capture a generated code)
        var r2 = rest.postForEntity(base + "/auth/forgot/request-otp", java.util.Map.of("phone", phone), ApiResponse.class);
        Assertions.assertEquals(HttpStatus.OK, r2.getStatusCode());

        // grab OTP from mocked Twilio capture using normalized E.164 phone
        String normalized = "+84" + phone.substring(1);
        String otp = sent.get(normalized);
        Assertions.assertNotNull(otp, "No OTP captured for phone: " + normalized);

        // verify otp
        var verifyReq = java.util.Map.of("phone", phone, "otp", otp);
        var r3 = rest.postForEntity(base + "/auth/forgot/verify-otp", verifyReq, ApiResponse.class);
        Assertions.assertEquals(HttpStatus.OK, r3.getStatusCode());
        // parse resetToken from response
        var data = (java.util.Map) r3.getBody().data();
        String resetToken = (String) data.get("resetToken");
        Assertions.assertNotNull(resetToken);

        // reset password
        var resetReq = java.util.Map.of("resetToken", resetToken, "password", "NewPass123");
        var r4 = rest.postForEntity(base + "/auth/forgot/reset", resetReq, ApiResponse.class);
        Assertions.assertEquals(HttpStatus.OK, r4.getStatusCode());

        // login with new password
        var loginReq = new com.example.hungdt2.auth.dto.LoginRequest("u_for_reset", "NewPass123");
        var r5 = rest.postForEntity(base + "/auth/login", loginReq, ApiResponse.class);
        Assertions.assertEquals(HttpStatus.OK, r5.getStatusCode());
    }

    @TestConfiguration
    static class TestBeans {
        @Bean
        public com.example.hungdt2.sms.SmsSender smsSender() {
            // no-op SMS sender for tests when Twilio is used
            return (phone, message) -> {};
        }

        @Bean
        @org.springframework.context.annotation.Primary
        public com.example.hungdt2.sms.TwilioVerifyService twilioVerifyServiceMock() {
            return org.mockito.Mockito.mock(com.example.hungdt2.sms.TwilioVerifyService.class);
        }
    }
}